### ISSUE TITLE
Hotspot 2.0 / Passpoint support (Windows 10 only)

### ISSUE THREAD

**Issue by restena-sw** [GEANT/CAT#10]
Windows introduced PassPoint support with Windows 10, see:

https://msdn.microsoft.com/en-us/library/windows/desktop/mt297479(v=vs.85).aspx

When an admin wishes Hotspot 2/ ConsortiumOI support, the appropriate XML tags should be added to Win10 installers.

**Comment by restena-sw** [comment]
TW investigated this in Aug 2016:

Initial testing
==========
I need to rum more tests to be absolutely sure. The results I got
yesterday were that when I simply added the whole block verbatim:

<Hotspot2>
   <DomainName>contoso.com</DomainName>
   <Network3GPP>
      <PLMNID>12345</PLMNID>
      <PLMNID>123456</PLMNID>
   </Network3GPP>
   <NAIRealm>
      <name>test1@contoso.com</name>
      <name>test2@contoso.com</name>
   </NAIRealm>
   <RoamingConsortium>
      <OUI>00AABB</OUI>
      <OUI>001122</OUI>
   </RoamingConsortium>
</Hotspot2>

then I was getting a schema error (!).
When I remove the Network3GPP element I no longer get the schema error,
but an mystrious 0x8008B error, which I cannot locate via Google. This
error disappears only when I limit the stuff to the RoamingConsortium
element.

Even if all of a sudden things get fixed by an update, we will still
risk that some not-so-up-to-date machines will simply break.

Further investigations
================
> it's an xs:sequence where the NAIRealm needs to come *before* Ntework3GPP.
>
> All elements are optional, so you only get the schema error if writing
> things out-of-order.
>
> So, their example is just slightly broken. Oh, well.

Indeed changing the order has removed the schema error, but left the
0x8008B one.

**Comment by restena-sw** [comment]
The hex error code did not occur when using a different Wi-Fi adapter (one which has proven support for Passpoint). After installing the profile, the profile name is displayed as operator name in UI. So this can work! I've sent the profile that works to Tomasz; along with instructions how to find out if a Wi-Fi adapter has Passpoint support:

netsh wlan show wirelesscapabilities

and then looking for the line "ANQP Service Information Discovery"

**Comment by twoln** [comment]
This feature has now been implemented and seems to work reliably.

**Comment by aseemkaushal** [comment]
Hi All

I am also facing error while provisioning Hotspot 2.0 profile on windows 10 via Online registration server(Hotspot 2.0 Release 2).
It initiates SOAP over https but when tthe profile is pushed on to the windows it shows schema validation error though the profile is as per the hotspot 2.0 specs.
Really appreciate if someone can suggest or if anyone had faced the same issue.

Thanks in advance.

**Comment by aseemkaushal** [comment]
> This feature has now been implemented and seems to work reliably.

https://github.com/GEANT/CAT/issues/10#issuecomment-622806262

**Comment by aseemkaushal** [comment]
https://github.com/GEANT/CAT/issues/10#issuecomment-622806262

**Comment by restena-sw** [comment]
I don't think #10 has anything to do with the implementation of HS 2.0 *in this project* ? I.e. our approach does not use SOAP, but netsh.
