### ISSUE TITLE
Static Configuration Tests - Certificate checking 

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#103]
# Issue type
- Questions about the eduroamCAT or its usage should be sent to the [users mailing list](https://lists.geant.org/sympa/info/cat-users).

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [X ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description

When running the static configuration tests it reports "The server certificate could not be verified to the root CA you configured in your profile!" even though the certificates match.

## How to reproduce issue

Install QuoVadis certificate and run the test.
 
## Detail of issue

See attached files containing the CAs as installed in the profile and a TAR of the temporary directory as requested.

```text
**copy/paste evidence or feature request here. No links to 3rd party sites.
```

[cert_tempdir.tar.gz](https://github.com/GEANT/CAT/files/1781286/cert_tempdir.tar.gz)
[CAs.tar.gz](https://github.com/GEANT/CAT/files/1781289/CAs.tar.gz)

**Comment by restena-sw** [comment]
I notice that the tarball of CA certificates does not contain openssl "c_rehash" hashes. Are you sure that c_rehash is available on your system and that you've set the corresponding config parameter in config-diagnostics:


        /**
     * Various paths.
     * eapol_test: absolute path to the eapol_test executable. If you just fill in "eapol_test" the one from the system $PATH will be taken.
     * c_rehash: absolute path to the c_rehash executable. If you just fill in "c_rehash" the one from the system $PATH will be taken.
     *   See also NSIS_VERSION further down
     * @var array
     */
    'PATHS' => [
        'c_rehash' => 'c_rehash',
        'eapol_test' => 'eapol_test',
    ],

**Comment by nevryn** [comment]
On Mon, Mar 05, 2018 at 07:07:06AM -0800, Stefan Winter wrote:
>    I notice that the tarball of CA certificates does not contain openssl
>    "c_rehash" hashes. Are you sure that c_rehash is available on your
>    system and that you've set the corresponding config parameter in
>    config-diagnostics:
>     /**
>  * Various paths.
>  * eapol_test: absolute path to the eapol_test executable. If you just fill in "
> eapol_test" the one from the system $PATH will be taken.
>  * c_rehash: absolute path to the c_rehash executable. If you just fill in "c_re
> hash" the one from the system $PATH will be taken.
>  *   See also NSIS_VERSION further down
>  * @var array
>  */
> 'PATHS' => [
>     'c_rehash' => 'c_rehash',
>     'eapol_test' => 'eapol_test',
> ],

It wasn't on the system. Now it is. That's certainly changed the output of
the tests. Thanks.

Mike

-- 
Mike Richardson
Currently on Secondment to JISC
*Plain text only please - attachments stripped on arrival*

**Comment by restena-sw** [comment]
Glad that this resolves the issue.
