### ISSUE TITLE
Realm Check: warnings in logs

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#104]
# Issue type
- Questions about the eduroamCAT or its usage should be sent to the [users mailing list](https://lists.geant.org/sympa/info/cat-users).

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [X ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description

## How to reproduce issue

Perform a static connection test for a realm
 
## Detail of issue

Whilst it all appears to work, these messages appear in the logs:

[Tue Mar 06 10:55:48.475520 2018] [:error] [pid 1425] [client 193.62.24.33:41912] PHP Notice:  Undefined index: CN in /opt/CAT/core/diag/RADIUSTests.php on line 646, referer: https://cat-beta.govroam.uk/diag/action_realmcheck.php?inst_id=3&profile_id=5
[Tue Mar 06 10:55:48.475600 2018] [:error] [pid 1425] [client 193.62.24.33:41912] PHP Notice:  Undefined index: sAN_DNS in /opt/CAT/core/diag/RADIUSTests.php on line 646, referer: https://cat-beta.govroam.uk/diag/action_realmcheck.php?inst_id=3&profile_id=5
[Tue Mar 06 10:55:48.475668 2018] [:error] [pid 1425] [client 193.62.24.33:41912] PHP Notice:  Undefined index: CN in /opt/CAT/core/diag/RADIUSTests.php on line 647, referer: https://cat-beta.govroam.uk/diag/action_realmcheck.php?inst_id=3&profile_id=5
[Tue Mar 06 10:55:48.475682 2018] [:error] [pid 1425] [client 193.62.24.33:41912] PHP Warning:  array_search() expects parameter 2 to be array, null given in /opt/CAT/core/diag/RADIUSTests.php on line 647, referer: https://cat-beta.govroam.uk/diag/action_realmcheck.php?inst_id=3&profile_id=5

```text
**copy/paste evidence or feature request here. No links to 3rd party sites.
```

**Comment by restena-sw** [comment]
I've pushed a fix, thanks!
