### ISSUE TITLE
Missing phpdoc data and odd line in Makefile

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#106]
# Issue type
- Questions about the eduroamCAT or its usage should be sent to the [users mailing list](https://lists.geant.org/sympa/info/cat-users).

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [ X] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description

No link to /phpdoc from Help->Documentation

## How to reproduce issue

Go to Help->Documentation on a fresh install.
 
## Detail of issue

It looks like the phpdoc directory and contents should be created by running 'make documentation' but the Makefile has the command "/home/swinter/packages/linux/phpDocumentor.phar" which isn't going to work (in general).

**Comment by restena-sw** [comment]
Worth noting that this requires phpDocumentor 3.0.0-alpha2 or higher. Since this is only done by people working directly on a git tarball rather than a packaged release, this is not included in the deployment guide.
