### ISSUE TITLE
Linux installer: Improve server certificate verification in fallback wpa_supplicant.conf

### ISSUE THREAD

**Issue by egroeper** [GEANT/CAT#131]
# Issue type
- [X] New feature request.

# Defect/Feature description

Linux installer uses altsubject_match on recent Network-Manager setups (>= 0.9), but only [domain_suffix_match](https://github.com/GEANT/CAT/blob/8e1554f03583cfb1121444b34bb5c66b36a7f38e/devices/linux/Files/main.py#L513) in the fallback wpa_supplicant.conf.
To me it seems like altsubject_match is available since 2006-11-24 (v0.5.6) so there should be no reason for not using it?
 
I looked into this because of https://github.com/GEANT/CAT-Android/issues/22.

**Comment by twoln** [comment]
alt_subject_match should be dropped if possible and replaced with domain_suffix_match. We are only using the first when we have no other option (this was the case for Network Manager, but should be revisited as things may have changed). Imagine that you have your server certificate provided by a public CA and your server name is radius.mydomain.edu. If someone sets up a server with a name radius.mydomain.edu.pl and gets a certificate from the same public CA then with alt_subject_match the client will accept this other server, which is not what you want. With domain_suffix you have a much better chance of controlling things.

**Comment by egroeper** [comment]
To me this seems more like a question of certificate compatibility than of wpa_supplicant compatibility (setting there since 2006).
And yes. I agree that nowadays all ssl certificates used for 802.1X should have an subj_alt_name extension.
If they don't have one, the NetworkManager config for recent systems wouldn't work either.

**Comment by twoln** [comment]
Indeed, and we never got a complaint, so there seems to be no problem with the server certificates. Besides, our test suite in CAT would pick this thins up as well (but only it the admin actually cares to do the run).

**Comment by twoln** [comment]
The current approach is to use alt subject_match exclisively.
