### ISSUE TITLE
Fine-Tuning options should be displayed only when pertinent

### ISSUE THREAD

**Issue by restena-sw** [GEANT/CAT#138]
# Issue type

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [ ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [X ] New feature request.

# Defect/Feature description

In the admin area, Installer Fine-Tuning, there are some fine-tuning options which are only pertinent to a specific EAP type or to a specific device.

Right now, the list of options displays all EAP-related options for all EAP types, even if they are not applicable to a subset of those; and analogous for devices.
 
It would be better to display an option only if it has an effect on the particular EAP method or device.

**Comment by restena-sw** [comment]
Options already have a "flag" field in the code. It is possible to add flags like "device=win10" and to restrict the option display only on a match. This however requires code changes I don't want to introduce during the current late beta phase.

So this is a feature for 2.0.1 or similar.

**Comment by twoln** [comment]
This has been implemented.
