### ISSUE TITLE
Linux installer fails with syntax error

### ISSUE THREAD

**Issue by torlasz** [GEANT/CAT#147]
# Issue type
- Questions about the eduroamCAT or its usage should be sent to the [users mailing list](https://lists.geant.org/sympa/info/cat-users).

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [x ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description
Running the installer results in syntax error:

File "./eduroam-linux-Semmelweis_Egyetem.py", line 949
    Messages.wrong_realm = "Hiba: a felhasználónévnek "xxx@{}" " \
                                                         ^
SyntaxError: invalid syntax

## How to reproduce issue
It occurs in Ubuntu 18.04, Python version: 3.7.1
 
## Detail of issue
it looks like single quotes should be used around xxx@{} instead of double quotes.
A similar problem is present in line 953 (Messages.wrong_realm_suffix) around {}

**Comment by twoln** [comment]
These are the Hungarian translation error which replaced original single quotes with double ones.

**Comment by torlasz** [comment]
Thank you, I should have thought about that. I'll try to have it fixed.
