### ISSUE TITLE
Windows installer fails to configure 2nd SSID

### ISSUE THREAD

**Issue by martinpauly** [GEANT/CAT#148]
# Issue type
- [x ] Defect - Unexpected behaviour (obvious or has been verified by a project member).

# Defect/Feature description
I recently added a profile with a second SSID. When trying to use it on Windows 10 1809,
it can see in the live log that the installer tries to handle the XML named after said SSID.
But the result never shows. 

## How to reproduce issue
Configure 2nd to SSID in a profile. Try Windows installer on test machine,
check if settings are in place.

## Detail of issue
To make things worse, a manual configuration using the "Identity protection" 
checkbox did not work either (in first attempt, the dialog even hung up I had to reboot).
The SSID simply never gets configured in any way.

**Comment by twoln** [comment]
After you have run the installer please run
netsh wan show profiles
If the second profile shows then most likely CAT did its job but there is something wrong with how this second SSID is set up on your access points.
Multiple SSID setup has been tested many times.
you could also run the installer from the command line with -DEBUG=4 and check the resulting log file.

**Comment by restena-sw** [comment]
That should be "netsh wlan show profiles" I guess (note the extra "l").

**Comment by martinpauly** [comment]
Arrrrgh! Mea culpa. I had a wrong assumption about Upper/Lowercase in the SSID name.
Sorry to bother
Martin
