### ISSUE TITLE
Do not use $HOME for dumping files, Follow XDG standards

### ISSUE THREAD

**Issue by rugk** [GEANT/CAT#150]
https://github.com/GEANT/CAT/blob/287ee386eeedc4ef7c33c26f33901151dfef40ec/devices/linux/Files/main.py#L308

See https://0x46.net/thoughts/2019/02/01/dotfile-madness/ for why.

The short summary is:
* placing all files in `$HOME` fills this directory
* for config files (and I would think the CA cert belongs to that category) please use `$XDG_CONFIG_HOME` instead
* This is specified in the XDG Base Directory specification, see https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html (and https://standards.freedesktop.org/basedir-spec/latest/)

Please adhere these standards. Filling `$HOME` with dirs or so is not a nice behaviour. Thanks.

**Comment by ikreb7** [comment]
@twoln You can close this issue.

**Comment by rugk** [comment]
Thanks for fixing it. :smiley: :+1: 

Next time, you can (automatically) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged by adding some "magic" text to your PR _body_.
