### ISSUE TITLE
Windows: Spaces in TEMP path lead to failed netsh calls

### ISSUE THREAD

**Issue by J-a-x-u** [GEANT/CAT#158]
If the username contains spaces, this will (on some occasions) lead to spaces in $TEMP:

`C:\Users\Firstname Surname\AppData\Local\Temp\wlan_prof-0.xml`

Which will cause netsh to fail: (CAT.log)
`Execute: C:\WINDOWS\sysnative\netsh wlan add profile C:\Users\Firstname Surname\AppData\Local\Temp\wlan_prof-0.xml'`
'netsh returned 1`

$TEMP should always be enclosed in quotation marks and

https://github.com/GEANT/CAT/blob/95e5a7d45d6cae7c53e725fe1cc29a917b5481fb/devices/ms/Files/common.inc#L938

and all other uses of $TEMP should be

`nsExec::Exec '"$Netsh" wlan add profile "$TEMP"\wlan_prof-$R0.xml'`

just like in

https://github.com/GEANT/CAT/blob/95e5a7d45d6cae7c53e725fe1cc29a917b5481fb/devices/ms/Files/common.inc#L253

**Comment by twoln** [comment]
Fixed that, however the TEMP path handling in Windows seems to be rather strange. My tests show that when you assign TEMP to en existing path that has elements which do comply to the 8.3 DOS convention then Windows automatically replaces them with  equivalents that are shorter and/or do not contain spaces. Only if you assign TEMP to a non-existent path and create the dir afterwords, then until you logout/login the TEMP has the space. I have tested the corrected installers and it seems to work fine, but I would be interested to see how such a space can appear in real-life situation.

**Comment by J-a-x-u** [comment]
I couldn't repeat this is my tests either, but with thousands of students and their laptops there is always the one or the other with that windows system that has a space in the TEMP path.

**Comment by twoln** [comment]
I fully agree and thanks for reporting this.

**Comment by restena-sw** [comment]
I understand that this was fixed in a recent commit to the 2.0.x branch. We are about to release 2.0.2 from that, which should hit production a few days later then.
