### ISSUE TITLE
802.1x on Wired interface settings locked Windows 10 (Build 1909)

### ISSUE THREAD

**Issue by Damster-J** [GEANT/CAT#185]
# Issue type
Defect - Unexpected behaviour (obvious or has been verified by a project member).

# Defect/Feature description

Using the CAT tool to configure 802.1x on Windows 10 Build 1909 wired interfaces imports successfully. However, users are not able to edit the configuration settings via Network and Internet settings | Change adapter options. Presented with error "The changes to Authentication setting could not be saved"

## How to reproduce issue

If provisioned in the CAT tool, execute and configure wired interfaces. Open Network and Internet settings | Change adapter options | Change any of the authentication settings and you should be presented with the error error "The changes to Authentication setting could not be saved"
 
## Detail of issue

If users want to make changes or disable Authentication on their device they are unable.

**Comment by twoln** [comment]
This appears to be a bug in this release of Windows which has been fixed in 2004, as @Damster-J sported himself. I believe this issue can be closed?

**Comment by Damster-J** [comment]
While the upgrade is a fix this may not be suitable as the update to Windows 2004 is unlikely.

**Comment by twoln** [comment]
But we are dealing with a rather obvious bug, and I do not see any workaround tor the problem. Calling netsh from PowerShell did not work for me. The problem does not seem to affect many people. Even if the institution admin sets wired eduroam, connections to non-secured networks will still work fine. Making changes to the profile via the CAT installer also works. 
It would seem that MS could just remove this bug in one of their fixes, perhaps we should push them a bit?
