### ISSUE TITLE
Feature Request: 802.1x wired configuration Windows "Wired AutoConfig" service startup type

### ISSUE THREAD

**Issue by Damster-J** [GEANT/CAT#186]
# Issue type
New feature request.

# Feature description
Using the CAT tool the enabled 802.1x authentication on wired interfaces starts the "Wired AutoConfig" service, enabling the Authentication tab of the network connection. Please consider including the function to set the startup type of the "Wired AutoConfig" service to automatic as it remains at Manual and we have found that this causes inconsistent authentication issues.

**Comment by twoln** [comment]
There is a simple bug. The service does get set up when a wired interface is configured together with a wireless one, but not when no wireless is found. This is already fixed in release 2.0 branch and will be pushed to master within the global rewrite of that device.
