### ISSUE TITLE
Make "Verify user input to contain realm suffix" default on

### ISSUE THREAD

**Issue by jornane** [GEANT/CAT#187]
# Issue type

Change request, the current defaults can be improved.

# Defect/Feature description

## How to reproduce issue

Make a new profile in CAT, **Verify user input to contain realm suffix** is off by default, and the admin has no incentive to turn it on. 
 
## Detail of issue

New eduroam supplicants like geteduroam use the eap-config file to decide whether to enforce the realm. Right now the default makes it so that CAT explicitly tells the app to not enforce the realm. In some cases this is correct, when the anonymous identity is set. But in other cases, there is no reason for this.

Because of this, **Verify user input to contain realm suffix** should be on by default, but we should still allow the administrator to disable it.

Additionally, it makes sense to update all profiles in cat.eduroam.org: If the anonymous identity field is not set, enable **Verify user input to contain realm suffix** for this profile.

Point for discussion: Should **Prefill user input with realm suffix** also be on by default (and enabled on existing profiles on cat.eduroam.org)? I think so, because it is the case for "simple" profiles; for advanced profiles, the admin has a bigger incentive to go over alle the settings and can disable that as well.

**Comment by restena-sw** [comment]
It is definitely a good idea to change the default to "yes, verify". Note that this has varying amounts of effect: it is optional for the IdP to provide the name of the realm at all. If they don't, the only verification that can be done is to check for the presence of exactly one "@". If the realm is provided, one can of course check more thoroughly on the suffix  @... .realm.

I have just checked the CAT prod database and am impressed by the power of defaults:

SELECT COUNT(*) FROM profile WHERE use_anon_outer = 0 AND verify_userinput_suffix = 0;
+----------+
| COUNT(*) |
+----------+
|     1898 |
+----------+

It is a good idea to change those entries in bulk as a one-off, but it means there is a behaviour change for almost 2000 profiles out there. Huh. The good thing is that the behaviour change is only going to be seen when the user is about to do something wrong, i.e. submit a username which is known bad. It will help to correct that input by the user; and that makes it a change worth doing. This will have to be pre-announced to the -users and -announce lists though, to make people aware that this is coming.

I'm more hesitant regarding the "Prefill". This will create a visible behaviour change for *everyone* using those profiles. It can also have an effect on helpdesks if they have documentation/screenshots in which the input box now looks different from before. I am wary of irritations caused by this, even if it is communicated to the -users list beforehand. The principle of least surprise should apply here IMHO.

**Comment by pauldekkers** [comment]
Maybe it depends on the way "prefill" is implemented? If there is an autocomplete if the realm is left out, that wouldn't interfere with the user-experience. If it's really a prefilled value that you have to prepend with your username, it can be bothersome indeed.

**Comment by restena-sw** [comment]
I am somewhat/much against auto-correcting things after-the-fact for the user. This leaves the wrong impression in users' minds that they have done the right thing. Once they use a different device, with a different installer or ad-hoc, they will do it again and it won't work then.

So I'm much more a fan of lecturing the user in passing - by showing him the important bits immediately.

That was at least the intention when calling the option *prefill* (not *postfill* ;-) ).

Having said that, my own device modules (macOS, ChromeOS) do not have the opportunity to prefill anything (using .mobileconfig and .onc formats, which don't allow actual interaction during authentication time). I would need to check with @twoln how e.g. the Windows module does this. Any insights from you @twoln?

**Comment by twoln** [comment]
Windows installers just pre-fill the input field.

And regrading changing the settings in the DB at this moment, this could break down things for people using more than one realm. I believe we may have such cases in Poland - schools change names and change the domains as a result.

**Comment by pauldekkers** [comment]
@twoln I presume these institutions don't have the prefill or verify options enabled, in that case? Or they create a different profile with new (enforced) values? Agree it could break things, though.

Maybe I rather interpret "prefill" as "hint". If the suggestion is shared, greyed out, "prefilled", but doesn't interfere with user-input, that would be nice to show the user the correct value. I guess there's a different in approaches by clients here (geteduroam, Windows installers, options in mobileconfig or not, Android CAT app), and that results in a difference on preference for this setting.

**Comment by restena-sw** [comment]
If there's possible breakage involved with the bulk DB change - let's not.

Changing the defaults for both of these options is not an issue though, and I will work on the code.

**Comment by twoln** [comment]
I was thinking more about verification than the pre-fill. With the verification turned on, the system will just no accept user's input if it does not end with the appropriate realm. Turning this option on for everyone would break things for people who have multiple realms and just use a single profile.

**Comment by jornane** [comment]
There seems to be a misunderstanding here. It was my understanding that if your realm is example.com, a user input such as bob@student.example.com would also be acceptable. In that case, enabling verify for everyone does not break except for weird institutions (which then can turn it off again)

**Comment by twoln** [comment]
As I wrote, the interface just checks that the user input ends with the given realm, so you are correct, adding a subdomain would not be a problem. What would cause problems would be institutions changing their domains completely, like we have switched from ncu.edu.pl to umk.pl a long time ago, but I have several fairly recent examples from Poland that such major changes happened. Such institutions keep using both realms for quite a long time and if I were in their shoes, I would supply the new realm tor outer identity but then accept both the old and the new as user identifier. Sure they should just have the realm validation turned off and no problem there, but if we just went into the database and arbitrarily set the validation option for everyone then this would cause problems.
Therefore changing the default for new profiles is fine and reminding people that it is possible to set this option is also fine, changing things for existing profiles is not.

**Comment by restena-sw** [comment]
As a first step, we should agree on what the desired semantics is at all. I've created a dedicated page in tutorials/MappingCATOptionsIntoSupplicantConfig.md in the master branch. Please review what I wrote there - it should be in line with our discussion so far - and especially for @twoln please fill in how the Windows and Linux modules behave in regards to those options. If they differ, we should either change the text on the page or change the implementation to match the text, depending on what we actually agree on :-)

**Comment by jornane** [comment]
I can't comment or commit to the document itself, so I'll write my comments here:

# What the geteduroam client does

Only setting `<InnerIdentitySuffix>` will make the user believe that realmless login is possible; if the given username does not contain @, it will silently append `@realm` when logging in. The user is not stopped, because this risks the user discarding the app and setting up eduroam manually. The eap-config file has indicated we should not give hints, so we don't do that.

Setting both `<InnerIdentitySuffix>` and `<InnerIdentityHint>true</InnerIdentityHint>` causes the username field to get a placeholder with the string `username@realm` (literal `username`). When writing, `@realm` disappears, since it is a placeholder. When the field loses focus without containing `@`, it will get `@realm` visibly appended to it.

In both cases, if the username field contains `@` but does not end with the realm, the user cannot continue. No error is displayed to the user, this is a bug.

# Comments on CAT

## Verify user input to contain realm suffix behaviour on realmless profile

`Verify user input to contain realm suffix` causes the following in eap-config:

	<InnerIdentitySuffix>example.com</InnerIdentitySuffix>

`Prefill user input with realm suffix` causes the following in eap-config:

	<InnerIdentityHint>true</InnerIdentityHint>

The CAT admin UI requires the former to be set for the latter. However, from the XML data it is apparent that `<InnerIdentitySuffix>` cannot be set without a realm being set, even though CAT allows me to check that checkbox without entering a realm. It still doesn't work, though; if I try to make a profile without a realm and I check `Verify user input to contain realm suffix`, I get the following error message and the checkbox is unchecked:

	Realm check username cannot be configured: realm is missing!

Apparently there is a bug in CAT where it allows setting the checkbox on a realmless profile, but not saving it. MappingCATOptionsIntoSupplicantConfig.md states that this is possible and even describes how clients should handle it, but it does not seem possible from the eap-config format and it does not seem possible from the CAT behaviour.

## Case sensitivity

Why should a realm check be case sensitive?

## Prefill or hint

The CAT interface names the checkbox `Prefill user input with realm suffix`, but in the eap-config file it's `<InnerIdentityHint>`. It is unclear for me how I should handle this. If `<InnerIdentityHint>` is not true (it is not set to false but disappears if the checkbox is unchecked), I would interpret that as that "no hint should be given".

# Should we change existing profiles?

Some profiles are wrong now, and might never be fixed. Some profiles would become wrong if we make the changes that were proposed. Profiles that neither specify a realm check nor an outer identity are already broken in my opinion; a user is able to enter a username without realm that can never work in eduroam. If there are Polish institutions that have changed their realm they should update their CAT profiles to reflect this so that their new users use the correct realm. They should not rely on the user entering a realm. When new users are required to use the new realm, the old realm will die out and they can decommission it. I don't see how this prevents us from changing the profiles, and if they have a strange reason they can revert the change to the profile (or Tomasz can do that for them)

# Different approach?

The current settings are confusing, as can be seen by my long message here and the long discussions we've had about it. We could consider dropping `<InnerIdentityHint>true</InnerIdentityHint>` and making a better configuration.

- Require a realm to be set (true/false/null, require/refuse/don't care)
- List of acceptable realms (list of strings, or regex if you want to be really fancy, should be possible to indicate whether subrealms are ok)
- Realm hint (string provided by the admin, visible as example in the login screen, does not need to match an acceptable realm, e.g. `<role>.example.com` to indicate that the user must pick a realm themselves)
- Default realm (automatically add to username in a visible way, unset to not add anything)

This would be a bigger change, but it gives flexibility to the admins, and from Tomasz answer I get the impression that such flexibility is needed sometimes. We should have sensible defaults though, which in my opinion would be:
- Require a realm
- Acceptable realms consist of only the profile realm, allowing subrealms
- Hint is identical to the profile realm
- Default is identical to the profile realm

**Comment by twoln** [comment]
One comment regarding the current implementation of Hint in Linux and Windows. We actually force the realm to be exactly as is provided in the realm setting. This behaviors might not be obvious from how it is described in the admin interface. We might discuss if we actually want this and if so then if we should change the description.
This remark does not take into account last comment posted by @jornane

**Comment by jornane** [comment]
> We actually force the realm to be exactly as is provided in the realm setting

How does this relate with the prefill/"hint" option? What would be a use case for requiring a certain realm but not prefilling it?

**Comment by twoln** [comment]
In my opinion if we hint to the users the realm by profiling it, it would be asking for trouble if we were also accepting other reals and expecting that some users will provide it. Currently we pre-fill the realm like: @umk.pl. Of course we may change either the wording in the admin interface or the implementation on the client side but this would need to be decided on.
Regarding the second question - not prefilling but requiring the exact realm - my use case would be to copy the scenario from other situation where our users take the whole username+realm as their university id. This is not terribly convincing though.

**Comment by jornane** [comment]
> it would be asking for trouble if we were also accepting other realms

But this cannot happen, because

> We actually force the realm to be exactly as is provided in the realm setting

In CAT, you cannot enable the prefill/"hint" option without also enabling requiring the realm.

Since there is no good reason to disable the prefill once requiring the realm is set, and since there is no way to enable the prefill once requiring is unset, I think we should drop the prefill setting and simply always prefill when a realm is required.

Please also take a look at my longer post where I propose a solution to this.

**Comment by restena-sw** [comment]
But we observe a mismatch here. geteduroam is currently doing a "suffix of realm must match" while our Windows installer apparently does an "exact realm match". In any case, the two behaviours should be aligned and the behaviour page I created should document the then-synced behaviour.

And then it depends on which of the two variants we would want to be the "right" one to sync to. (IMHO it is the suffix-match, not the exact match, but that's up to discussion)

If we decide towards "suffix-match" then a spearation of verify vs. hint still makes sense because hinting for sub-realms doesn't work - we don't know all the sub-realms, and can't prefill with all of them at the same time.

If we decide towards "exact match" then indeed separating between verify-only vs. hint does not have a valid use case any more and can get removed.

So, what do you think? Verify against suffix of realm, or on the exact realm, what should be our intended behaviour?

**Comment by twoln** [comment]
The exact match is implemented only for the hinting case, the suffix alone is also available without pre-filling.

**Comment by restena-sw** [comment]
Do I understand this correctly? 

If "verify" is set but "hint" is not, the verification is doing a suffix match, allowing sub-realms. 
If both "verify"and "hint" are set, the verification is doing a check on the exact realm as entered.

That indeed makes the most out of the inputs provided by the admin. It makes "hint" something on top of "verify" - it will do all the things verify does, and more.

I can't say it's conceptually very clean - the naming of the option suggests its about UI only, but it does more than UI then. But still, it makes sense just as we discussed before: if an admin wants the realm to be hinted, then a more liberal verification with sub-realms doesn't make sense, so tightening it up is the thing to do. 

@jornane what do you think of this?

**Comment by twoln** [comment]
I confirm that the implementation in the installers is as you described.

**Comment by jornane** [comment]
@restena-sw I think we should at the minimum change the names of these settings, it's really confusing now as illustrated by this long discussion. Did you read my proposal? I think we can have separate settings for:

* Require a realm to be set (true/false/null, meaning require/refuse/don't care)
* List of acceptable realms (list of strings, if starts with . subrealm is ok)
* Realm hint (string provided by the admin, visible as example in the login screen, e.g. <role>.example.com)
* Default realm (automatically add to username in a visible way if user provides no realm, unset to not add anything)

**Comment by jornane** [comment]
This issue has now been stale for one week. Should we discuss this on the next eduroam development VC? It is unfortunate though that it has been postponed so much.

**Comment by restena-sw** [comment]
Renaming is indeed a good idea. Considering that "prefill" is actually doing something on top of "verify suffix", how about:
(verify=) "Enforce realm in username: Level 1"
(prefill=)"Enforce realm in username: Level 2"

This could be a drop-down that also has a Level 0, and equals that no verification is supposed to happen. The drop-down would also get a pop-up help that explains what the levels do. It would default to Level 1 (check syntactically correct, and suffix matches if realm is configured)

I have to say I'm somewhat against "list of realms" because it is uncommon for an IdP to have multiple entirely distinct realms (i.e. beyond multiple sub-realms with a common suffix) and asking every IdP in the UI for a list is not easy to understand in itself for many.

Also, regarding "default realm" this is pretty much the same as Level 2 (verify exact realm, prefill) except that it is not communicated to the user that a realm is required. And communicating that as some form of user education is actually desirable IMHO (for example because the user may need to configure multiple devices, and will learn the correct format in this particular CAT installer because seeing it in front of him).

**Comment by jornane** [comment]
It's not clear what the different levels mean without a good description besides the dropdown what they mean. If you don't want to change any schema here, just the UI, I would opt for

[ ] Require realm in username
[ ] Allow subrealms

Where the last checkbox would be the inverse of what's in the schema, but it's clear at a glance what these settings do.

A "list of realms" would seem necessary after reading this comment:

> Such institutions keep using both realms for quite a long time and if I were in their shoes, I would supply the new realm tor outer identity but then accept both the old and the new as user identifier

The list can be implemented as a setting in CAT, "Secondary realm", of which the admin can add multiple. It wouldn't be the first advanced feature in CAT that's not for everyone, but nice to have for those who need it.

A "default realm" can still be communicated to the user. You can add the realm to the username input field when it loses focus. If you want to draw more attention you can also make the background yellow when the software made a change to the input, this is also what browsers do when filling in passwords. This way, you educate the user and you make it easy to use the software.

**Comment by restena-sw** [comment]
I've implemented (but not ocmmited) a first go at this.

First off, the realm options have always been a bit cluttered: the input "realm" has an effect both for outer identities, and for inner identities (i.e. the actual passwords). So I've rearranged the checkboxes into the two categories.

Then I've renamed the two options roughly along your suggestion. The essential difference between the first and the second is that one operates on the realm *suffix* while the other one is on the *exact* realm.

So I thought why not use those words - see attached for the result.

 
![Screenshot_20200618_120117](https://user-images.githubusercontent.com/6346943/85007288-9b11d980-b15b-11ea-937d-882326e18555.png)

At this point "hint" or "prefill" is nowhere in the text, and probably it should never have been. After this long discussion, maybe it's best to leave the way how the realm gets attached to the username to the actual supplicant implementation (de facto, it is, given that Apple installers don't allow you to do anything anyway, no matter what you set).

So if you want a UI box that prefills the input field and positions the cursor - fine. If you want to sanity-check the given input at a later point, also fine.

**Comment by restena-sw** [comment]
And regarding

> A "list of realms" would seem necessary after reading this comment:
>>    Such institutions keep using both realms for quite a long time and if I were in their shoes, I would supply the new realm tor outer identity but then accept both the old and the new as user identifier

My take on it is: if you are in such a special situation you can just as well turn off "enforce realm suffix".

**Comment by jornane** [comment]
I think it's a good idea to leave the exact interpretation to the UI. The text in the CAT UI also seems fine.

Should we make changes to the eap-config format to reflect what we've discussed? Setting both will currently yield `<InnerIdentitySuffix>example.com</InnerIdentitySuffix>` (which is fine) and `<InnerIdentityHint>true</InnerIdentityHint>` (which is confusing)

**Comment by twoln** [comment]
We should consider what problems the schema change could cause and if adding a new tag might create validation errors in some implementation. I guess probably not and we could certainly test this.
I am OK with changing the wording and definitions.
About the proposed admin GUI change. The Enforce exact realm looks like attached to Other Identity for Realm Checks I find this quite confusing.

**Comment by restena-sw** [comment]
Screenshots:
![Screenshot_20200618_150709](https://user-images.githubusercontent.com/6346943/85034998-fc00d800-b182-11ea-8cc3-a65ea7b1b7c7.png)
![Screenshot_20200618_163718](https://user-images.githubusercontent.com/6346943/85035006-fe633200-b182-11ea-8e39-c8ade9f0189d.png)
![Screenshot_20200618_163802](https://user-images.githubusercontent.com/6346943/85035018-00c58c00-b183-11ea-941f-9e634ad81a97.png)

**Comment by restena-sw** [comment]
Since the "no realm set, but verify is checked" was buggy before it would probably be wise to check the device modules how they behave when this situation occurs.

**Comment by zmousm** [comment]
How, if at all, is the User API (response) affected by these changes?

**Comment by restena-sw** [comment]
The User API is not affected at all; these are changes to the UI and attribute semantics on the *admin* side only.

Arguably, the name of the option in *Admin* API is now also confusing (internal:hint_userinput_suffix) so let's talk about that together with the requested schema name change.

**Comment by restena-sw** [comment]
> We should consider what problems the schema change could cause and if adding a new tag might create validation errors in some implementation. I guess probably not and we could certainly test this.
> I am OK with changing the wording and definitions.
> About the proposed admin GUI change. The Enforce exact realm looks like attached to Other Identity for Realm Checks I find this quite confusing.

I suggest to discuss schema changes in a separate, new issue (I'll open one) - after all the request to add "Remove/Disable SSID" in #189 would also mean a schema change.

**Comment by restena-sw** [comment]
With the bug fixed, semantics clearly defined, rewording of the option in UI, and pick-up of new semantics in at least one device module (mobileconfig), this issue is mostly complete. What remains is the requested schema change which will be tracked in a separate issue. This issue will be referenced there.

**Comment by jornane** [comment]
Not so fast @restena-sw ;) I still think we should do an update of the database, where we enable realm checks for every profile where the outer identity is not set. Not doing so will cause users to be able to log in realmless on existing profiles.

I know @twoln is against this, due to some strange situations with some Polish institutions. But I think the gain is bigger than the pain in this case. We can warn institutions and NROs about the upcoming change, and tell them to get their profiles in order. If they set an outer identity, we won't touch their profiles. If they ignore us, we will fix their profiles for them.

For bonus points: Maybe we should make it impossible to make a profile that lacks both outer identity and realm checks, or at least give a warning when you do that. A profile like that does not make sense in eduroam, except maybe for internal testing.

(I can't reopen the issue, but I think it should not be closed yet)

**Comment by twoln** [comment]
I suggest that we stop discussing operational issues here. This is not about code therefore does not belong to GitHub.

**Comment by jornane** [comment]
Fair enough, we can discuss updating the database on the mailing list.

@restena-sw What will the default setting be, aka will the checkboxes be checked when creating a new profile?

**Comment by restena-sw** [comment]
I don't think I was particularly too fast, as the suggestion to have a warning on suboptimal settings was not ever in this thread, right?

I tagged commit https://github.com/GEANT/CAT/commit/94847194395a84a57b4c9c9a4e7223174167e24f to this issue 22h ago to make folks aware: yes, the default has changed.

I'm sympathetic to adding a warning if no anon ID is set and the admin does not want verification. I'm against making it impossible though- CAT has always been about enabling people to do the right things, not standing in their way.

So, happy to reopen the issue for a few minutes until the warn-about-lack-of-verification is implemented :-)

**Comment by jornane** [comment]
Very nice! :) I missed that you mentioned this issue in the commit, so that was my main reason for asking for more information. Warning when making a non-sensible profile was not in the initial issue, but it's closely related.

I agree that the issue was fixed with commit 9484719, and I'm happy with the warning.

Thanks @restena-sw, nice work 👍

**Comment by restena-sw** [comment]
The warning is now implemented and pushed to branch. See screenshot.
![Screenshot_20200619_143718](https://user-images.githubusercontent.com/6346943/85133298-bacbff00-b23a-11ea-92e9-b8bf8b9c9bdf.png)
