### ISSUE TITLE
AbstractProfile::CA_CLASH_ADDED fires when replacing a cross-signed intermediate with a root CA by the same name

### ISSUE THREAD

**Issue by zmousm** [GEANT/CAT#221]
# Issue type

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [x] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description
If one configures a CA and then replaces it with another by the same name (subject), `AbstractProfile::significantChanges()` adds `AbstractProfile::CA_CLASH_ADDED`, which triggers a warning by e-mail to be sent to the respective federation admins.

This also happens when a user first configures a cross-signed intermediate CA and then replaces it with a root CA by the same name, however this is perhaps a false positive alert considering that cross-signing a new CA with an existing trusted root while or before deploying the former as a new root is common practice. If so, when a user eventually replaces the former with the latter, this should not trigger such an alert.

## How to reproduce issue
* Configure a profile with this intermediate CA: http://repo.harica.gr/certs/HaricaCrossCertificate2011-2015.pem
* Subsequently replace the former with this identically named root CA: http://repo.harica.gr/certs/HaricaRootCA2015.pem
* Notice a significant changes e-mail alert is sent to respective federation admins

**Comment by restena-sw** [comment]
A modified PR that dis-arms the alert only if the public key of both old intermediate and new root match has been requested.

I have one question regarding the specific example you gave though:

The above old config with an intermediate CA is *not sufficient* info to configure the supplicant. The root of trust has to be a root CA, and if none if uploaded, it is not even possible to generate installers.

So your CAT profile certainly contained both the intermediate above *and* its root?

Now considering that intermediates are optional anyway, there is no way to silence this alert if only the old root is present in config, and a new root is added (i.e. with no intermediate to replace). But I understand you realise that, and really only care about changes of intermediate vs. root.

**Comment by zmousm** [comment]
Thanks @restena-sw 

I can not be sure how the profile (which originally triggered this observeration) was configured, as I did not do this myself, however we can rather safely assume it also included the (cross-signing, old) root: http://repo.harica.gr/certs/HaricaRootCA2011.pem

I understand your comments wrt only having the root in the profile configuration, but I think the particular alert would not trigger in that case as the SHA1 fingerprint would be different.

**Comment by restena-sw** [comment]
That's correct, it would trigger the normal "a new root CA was added" without the particularly alerting words (because the *name* is different).
