### ISSUE TITLE
French translation : tooltips text is truncated

### ISSUE THREAD

**Issue by arnaudlauriou** [GEANT/CAT#223]
Hello,

# Issue type

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [X] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description

With the French translation, the text of the tooltip is truncated at the first match of the ' character. 

Example with web_admin.po for overview_idp.php :
Original tooltip text : "Ce profil est affiché dans l'interface de téléchargement de l'utilisateur."
Tooltip text displayed : "Ce profil est affiché dans l"

Regards,

**Comment by restena-sw** [comment]
Hi! A classic... single quotes may be in need of escaping depending on the string delimiter in the source. I have changed the translation in the Transifex sources, so this string is going to be fixed in the next release.

Thanks!
