### ISSUE TITLE
Wrong jQuery reference

### ISSUE THREAD

**Issue by markusmarkusz** [GEANT/CAT#231]
# Issue type
- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [ ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description
In serveral places there are references to jQuery.js, for example:
https://github.com/GEANT/CAT/blob/d62009c0f06ba0c702fe2c16b321bd8de8fe6516/web/skins/modern/index.php#L31
But I can only find a [jquery-3.3.1.min.js](https://github.com/GEANT/CAT/blob/master/web/external/jquery/jquery-3.3.1.min.js)

Accessing the web page obviously produces an error that jquery.js can't be found.

## How to reproduce issue
Clean CAT installation based on [ansible playbook](https://github.com/GEANT/CAT/blob/master/ansible/ManagedWeb.yml) and [Configuration.md](https://github.com/GEANT/CAT/blob/master/tutorials/Configuration.md) and then accessing the web page.

## Detail of issue
So I'm not 100% sure if I miss something or if I have configured something wrong, but at the moment I don't see an mistake on my site. (maybe I just don't find it?)

Possible ways to fix this would be linking jquery.js to jquery-3.3.1.min.js, changing the relevant places in CATs source code or adding jquery.js. (or anything else, there are many ways to fix this if it is a bug)

I would be grateful if someone would either explain to me where my mistake is or fix this error, if it is one.

**Comment by restena-sw** [comment]
The instructions indeed miss a symlink "jquery.js" that is to be created to the most current jQuery version. I will update the Configuration.md

**Comment by markusmarkusz** [comment]
@restena-sw 
> The instructions indeed miss a symlink "jquery.js" that is to be created to the most current jQuery version. I will update the Configuration.md

Wouldn't it be much better to provide a suitable version (e.g. the already existing 3.3.1-min) or to obtain jQuery directly using [composer](https://packagist.org/packages/components/jquery)?

**Comment by restena-sw** [comment]
Well we update to the most current version whenever we make a tarball release. This would be sth like 3.6.0 next time.

But composer sounds interesting. I didn't know jQuery was available on composer. I'll investigate this, thanks.
