### ISSUE TITLE
RFE: Add clickable link in administrator management dialogue for improved speed of use

### ISSUE THREAD

**Issue by teamktown** [GEANT/CAT#239]
# Issue type
- [x] New feature request.

# Defect/Feature description
It would be a great accellerator/shortcut to have the link to manage the entity I just took control of if I am in the list!

Without it:
![image](https://user-images.githubusercontent.com/2530804/168096268-46e98e3f-dfa2-4ba1-a032-1473c091d61a.png)

and if it existed _after_ I click take control and added as an admin a link or button to manage the IdP would save many NRO admins helping their sites a  large amount of time!

We often have to do this to assist sites setting up their profile..

**Comment by nsp-devel** [comment]
Trying to understand what helps you best here... wouldn't it be quickest to immediately take you to the IdP's overview page, immediately after clicking the "Take control" button?

**Comment by teamktown** [comment]
sorry for delay. I'm ok with that -- target new window? Sometimes NRO's are working on multiple org items and need to 'take control' of numerous ones.  Jumping to them is fine but in opening a new window, I don't loose my 'spot' in the NRO view which takes quite a bit of time to render with 100's of rows sometimes.

**Comment by restena-sw** [comment]
Turns out it was only easily possible to do this the way you initially described; further automation of the redirect with header() does not allow to express the "new page please" - but it's easy with a plain ol' <a> tag and _blank target.
