### ISSUE TITLE
DeprecationWarning: distro.linux_distribution() is deprecated

### ISSUE THREAD

**Issue by samvang** [GEANT/CAT#242]
# Issue type
- [ ] Defect - Crash/memory corruption.
- [x] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [ ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description
Running the installer on Ubuntu 22 results in a `DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.`

## How to reproduce issue
Run installer on Linux with a recent version of Python
 
## Detail of issue
`distro.linux_distribution()` has been formally deprecated (https://github.com/python-distro/distro/pull/296)
The function is called in `get_system()` and this seems to be only used for debugging.

**Comment by twoln** [comment]
This comment is probably based on the behaviors of the current installer. The get_system function has been modified in the master branch is not generating this warning now.
