### ISSUE TITLE
Missing Translation DOWNLOAD_FOR_MESSAGE

### ISSUE THREAD

**Issue by mabezi** [GEANT/CAT#244]
# Issue type
- [x] Defect - Unexpected behaviour (obvious or has been verified by a project member).

# Defect/Feature description
Translation for `DOWNLOAD_FOR_MESSAGE` is missing.

## Detail of issue
Translation is referenced: https://github.com/GEANT/CAT/blob/d8644f85529abe70cb9a3f07d048f4c0924bdef7/web/skins/modern/user/js/cat_js.php#L102

Obviously produces an error:
`PHP Fatal error:  Uncaught Error: Undefined constant "web\\lib\\user\\DOWNLOAD_FOR_MESSAGE" in /var/www/html/web/skins/modern/user/js/cat_js.php:102\nStack trace:\n#0 /var/www/html/web/skins/modern/index.php(66): require()\n#1 /var/www/html/web/index.php(38): require('...')\n#2 {main}\n  thrown in /var/www/html/web/skins/modern/user/js/cat_js.php on line 102`

Maybe I'll take a look at it by myself if I find enough time.
Perhaps you meant `DOWNLOAD_MESSAGE`?

**Comment by twoln** [comment]
The text templates file has not been uploaded to git ad this causes he error. Will fix that tomorrow.
