### ISSUE TITLE
Remove CAT settings under Linux

### ISSUE THREAD

**Issue by steve4444** [GEANT/CAT#249]
# Issue type
- Uninstall/remove CAT settings

- [x] New feature request.

# Feature description
I have installed the CAT settings through the python script  `CAT/devices/linux/Files/main.py`, customised for my connection site, under Arch Linux.
Having finished my tasks, I am *unable to find an uninstaller*.
Where can I find a tool or a tutorial to uninstall the product and restore the original configuration?   
If this is not available, could you briefly outline impacted system settings, for a subsequent manual removal.

## How to reproduce issue
Install CAT settings with the python script for Linux and try to restore original settings.

**Comment by restena-sw** [comment]
On short-term: you can remove the settings with the NetworkManager UI (typically found in the system tray) and additionally can delete the ~/.cat directory, where the filesystem-based artifacts are stored.

Longer-term, I guess it would be more intuitive to add a "-u" switch to the installer script which does the same.

**Comment by twoln** [comment]
Well, the script simply configures the WiFi, as do all other CAT installers on other platforms. On no other platform CAT provides a feature to delete eduroam profiles, the user is expected to "forget" the network via the system settings. Exactly the same approach is possible in Linux, so unless we decide to create "uninstaller" for all platforms I would not see this as a priority.
