### ISSUE TITLE
French Translation - Tooltip Problem on Profile Status Indicator

### ISSUE THREAD

**Issue by EdKingscote** [GEANT/CAT#265]
# Issue type

- [X] Defect - Unexpected behaviour (obvious or has been verified by a project member).

# Defect/Feature description

There appears to be a bug with handling quotes in the French translation, causing truncated display and malformed HTML.

## How to reproduce issue

On an Organization Overview page that has an unpublished profile (https://cat.eduroam.org/admin/overview_org.php?inst_id=XXX), hover over the yellow exclamation mark with the language set as Francais and observe the truncated string in the tooltip. This is also reproducible on the cat-test site as of the time of writing.

Inspecting the HTML using the browser developer tools shows mis-matched quotes and content leaking in to the HTML tag etc.

## Detail of issue

It appears that the escaping for '  may not be behaving as expected

**Comment by restena-sw** [comment]
Some ' characters were not escaped. Fixed that, will be in 2.1.1.
