### ISSUE TITLE
Difference between eap-generic and eap-config-full can be confusing

### ISSUE THREAD

**Issue by jornane** [GEANT/CAT#271]
# Issue type
- Questions about the eduroamCAT or its usage should be sent to the [users mailing list](https://lists.geant.org/sympa/info/cat-users).

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [X] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description

## How to reproduce issue

Create a profile that contains custom RCOIs and attempt to configure the profile using the geteduroam app directly, and attempt to configure the profile by downloading it from the CAT website and sideloading it in the geteduroam app.

When sideloading, the RCOIs are not configured. When configuring from within geteduroam, the RCOIs are configured successfully.
 
## Detail of issue

Originally, we had two separate eap-config types; `eap-config` for the eduroamCAT Android app, and `eap-generic` for geteduroam; the only difference between the two being how TTLS-MSCHAPv2 was being represented (#191), but with the introduction of OpenRoaming, we have also gotten a new `eap-config-full`; a format that is better suited for giving users a choice whether to accept the OpenRoaming EULA, but not yet supported in any of the apps.

Yet, when downloading an "EAP config" installer from cat.eduroam.org, you get an .eap-config file in the `eap-config-full` format. This format puts all RCOIs in a separate `<EAPIdentityProvider>` element, **even - and this is the problem - the RCOIs that are set manually in the profile**. The geteduroam app ignores all but the first `<EAPIdentityProvider>` and configures it.

The user however (typically an admin in this case), expects geteduroam to behave the same whether the profile was chosen through the in-app discovery, or through downloading from CAT and installing the .eap-config.

Proposed solution is to either make cat.eduroam.org offer `eap-generic` files when downloading "EAP config" instead of `eap-config-full`, or to update `eap-config-full` so that they are logically identical to `eap-generic`, meaning that everything that is explicitly set in the profile, MUST be present in the first `<EAPIdentityProvider>` of the .eap-config file.

**Comment by twoln** [comment]
Perhaps I am missing something here.
First of all - the names you quote are just internal identifiers (which appear in direct download links). The admins and users can only see device names being: "Android 8 and newer", "Android 4.3-7", "EAP config". All other devices are hidden and can only be accessed with direct links.
Once a device name is defined it should probably stay in (possibly as an alias) for backwards compatibility, to keep these deep links working. 
I think that we have agreed that getedurom would be using one of these names only and this is completely inside the app, therefore I do not see where the confusion comes into play.

**Comment by jornane** [comment]
geteduroam can, in addition to the all-in-one app flow, also sideload .eap-config files that have been downloaded through a webbrowser. This flow is sometimes used by administrators to test their profiles.

In this flow, the administrator downloads the "EAP config" file, assuming it's the same one that geteduroam downloads by itself. Since the file is a different one, geteduroam behaves differently with the sideloaded file and with the file it would have downloaded itself.

That geteduroam uses .eap-config files internally has become a bit of a public secret, but not many people know that CAT can generate more than one variation of this file, and neither do they know that the one geteduroam uses is not the same one that CAT offers "EAP config".

If your argument is that, since geteduroam can download the profiles themselves and it thus can be hidden, then I wonder why the "EAP config" device is visible at all; there is no client that supports this format. In that case, the "EAP config" device should just be hidden.

**Comment by restena-sw** [comment]
This is more like a config change than an issue with code. It sure makes sense to hide the "EAP Config" button from the end-user download interface in the prod deployment.

Note that what you wrote in the previous comment " the administrator downloads the "EAP config" file, assuming it's the same one that geteduroam downloads" can still happen. We only hide devices from *end users* but not from administrators. They have their own download interface which always lists all devices.

@twoln will do the config change, and that closes the issue.

**Comment by twoln** [comment]
Actually there are to levels of hiding. Some stuff we also hide from the admins. Sun "deeply" hidden devices are still available for direct downloads.

**Comment by twoln** [comment]
This "full" config is now gone from the users' interface but left for admins. One of the config settings for this config is the OpenRoaming support, but this is not very relevant at the moment.

**Comment by jornane** [comment]
The admin interface still shows "EAP config" as the description of the file, and can thus still mistakenly assume that this is the same file that geteduroam is downloading.

Would it be possible to use a less generic name than "EAP config" for the eap-config-full device, and add the eap-generic device type to the admin page with a name like "geteduroam"?

**Comment by twoln** [comment]
Every name that is used on the main users interface will be repeated on the admins interface. We can add new names for admins only but will this not generate more confusion?

**Comment by jornane** [comment]
As per Stefan's comment, there is no reference to any eap-* device in the main users interface anymore. This name change will therefore only reflect in the admins interface; there is no need to use separate names for the different interfaces.

**Comment by jornane** [comment]
As an aside, it's easy for geteduroam to start using a different device type than eap-generic, if you would rather make a, say, eap-config-geteduroam, rather than branding eap-generic as geteduroam.
