### ISSUE TITLE
Linux installer fails on current Ubuntu 23.04

### ISSUE THREAD

**Issue by sklemer1** [GEANT/CAT#277]
# Issue type

At least vanilla Ubuntu 23.04 doesn't come with a `python` executable but only `python3`. We should somehow detect and react on this.

- [x] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [x] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description

## How to reproduce issue

Try to open CAT Linux installer on freshly installed Ubuntu 23.04.

**Comment by paolopertino** [comment]
I am not sure it is linked to this, but I have issues while trying to install my university certificate when using the provided script. I am also running Ubuntu 23.04 and one of the messages that pops up is "NetworkManager configuration failed, but we may generate a wpa_supplicant configuration file if you wish. Be warned that your connection password will be saved in this file as clear text. Continue?". I checked through logs and the network manager looks like it is fine... Is there a quick fix for this? Should I open another issue with more specifications?

**Comment by sklemer1** [comment]
this is unrelated

**Comment by twoln** [comment]
This script used to check for python versions but at some stage one of the contributors deleted this part of the code just leaving information I the comment.

The problem can be that we have 
#!/usr/bin/env python
 in the first line. Should change it to python3, I guess.
I never really cared as it seemed to me that people would just run it from the command line without making it executable and then running - seems to be too much hustle.

**Comment by sklemer1** [comment]
I can't judge how people are using it -- but we got one person to complain about this issue so I thought, I fire it here :). I think in 2023, some years after even Red Hat dropping support for python2 it's fair to put python3 into the shebang.

**Comment by twoln** [comment]
This is already done, so I guess we can close this?

**Comment by sklemer1** [comment]
Yep.
