### ISSUE TITLE
Bad handling of a missing dbus python module

### ISSUE THREAD

**Issue by horrovac** [GEANT/CAT#287]
I just spent an (embarassingly) long time trying to use CAT to configure my nm connection. Turns out, I was missing the dbus python module, and the message that the NetworkManager configuration failed was not helpful at all. Telling the user **why** it failed would have been more useful.

I suggest including this info in the error message or at least issuing a warning at the start. Both suggestions included in the patch attached.

[dbus-missing-message-patch.txt](https://github.com/GEANT/CAT/files/13556802/dbus-missing-message-patch.txt)

**Comment by twoln** [comment]
Warmings implemented.
