### ISSUE TITLE
Constant FILTER_SANITIZE_STRING is deprecated

### ISSUE THREAD

**Issue by Catwoolfii** [GEANT/CAT#288]
- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [x] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description
In current code uses the FILTER_SANITIZE_STRING filter, which is no longer supported since PHP v.8.1.

## How to reproduce issue
Immediately with any requests to the page, the following errors are displayed in the logs:
```
FastCGI sent in stderr: "; PHP message: PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /opt/cat/core/common/Language.php on line 119" while reading upstream
```

**Comment by restena-sw** [comment]
This is not an error, it's a mere deprecation warning. It's well noted that the particular constant here is going away at some point in the future, and I will keep the issue open until the uses are removed.

**Comment by twoln** [comment]
All appearances of FILTER_SANITIZE_STRING have been replaced with other code.
