### ISSUE TITLE
Use gender-neutral terms in English (where possible)

### ISSUE THREAD

**Issue by spaetow** [GEANT/CAT#289]
The translation at https://github.com/GEANT/CAT/blob/864c12269e6909d9b4ba55ceffda886ba3e23152/translation/core.pot#L520 uses 'him' to refer to the administrator. 'Them' is the gender-neutral third person to use in English (to also include 'her' for female admins, and any non-binary terms). :-)

**Comment by Kangie** [comment]
Resolved by the linked commit; @restena-sw could you please close?

**Comment by restena-sw** [comment]
done
