### ISSUE TITLE
missing elements in SQL schema update when upgrading 2.0.x to 2.1.1

### ISSUE THREAD

**Issue by restena-sw** [GEANT/CAT#295]
# Issue type
- [X] Defect - Unexpected behaviour (obvious or has been verified by a project member).

# Defect/Feature description

Many column names in the schema had a column "row" renamed to "row_id". This is not included in the schema upgrade scripts.

## How to reproduce issue

1) Upgrade a 2.0.x installation to 2.1.1.
2) observe error log entries like the following:

```
[php:error] [pid 21690] [client 2a00:6020:5047:4300:8afa:b791:ba5e:c37d:57288] PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown column 'row_id' in 'field list' in /var/www/CAT-2.1.1/core/DBConnection.php:149
```
 
## Detail of issue
The following updates fix the issue:

```
alter table federation_option rename column row to row_id;
alter table institution_option rename column row to row_id;
alter table profile_option rename column row to row_id;
alter table user_options rename column row to row_id;
```

**Comment by twoln** [comment]
Fixed
