### ISSUE TITLE
Enhancement Request: Add key size to certificate output in static connectivity test 

### ISSUE THREAD

**Issue by EdKingscote** [GEANT/CAT#297]
# Issue type

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [ ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [X] New feature request.

# Defect/Feature description

Whilst the server certificate details output in the static connectivity tests on CAT outputs a lot of useful information, it doesn't include the key size. It would be great to expose this to enable all visitors to this results page to have visibility to easily review and decide whether it meets best practices.

**Comment by majagw** [comment]
Done for release 2.1.2
