### ISSUE TITLE
Linux installer (Python script) exception when importing OpenSSL: AttributeError

### ISSUE THREAD

**Issue by KenanHanke** [GEANT/CAT#299]
# Issue type

- [x] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [ ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description

The Linux installer crashed with an AttributeError when importing OpenSSL inside a try block that only catches ImportErrors. I will fix this myself in a pull request.

## How to reproduce issue

Cannot currently reproduce because I've done a `pip install -U pyopenssl` since I had the issue and that also fixed it. I don't intend on spending hours testing old OpenSSL versions on my machine trying to find the broken one. However, before I did the pip install, I modified one line of code in the installer and everything worked as it should have. I believe the fix should be included in the project in order to let the installer run on all devices, even ones with an outdated/broken OpenSSL library.

## Detail of issue

Around line 100 in `devices/linux/Files/main.py` we have the following code:

```
try:
    from OpenSSL import crypto
except ImportError:
    CRYPTO_AVAILABLE = False
```

The import statement raised an AttributeError, crashing the entire script. With the following change, everything works as expected:

```
except (ImportError, AttributeError):
```

I will create a pull request for this myself.

**Comment by twoln** [comment]
Implemented in release_2_1.
