### ISSUE TITLE
Request for NRO view to show who the existing admins are

### ISSUE THREAD

**Issue by spaetow** [GEANT/CAT#306]
# Issue type
- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [ ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [X] New feature request.

# Defect/Feature description
As NRO admins it would probably be nice to know who the other NRO admins are, and if necessary, be able to remove them (or at least request that they are removed).

Right now the NRO view does not show any other admins, it would be nice to have this (similar to the organisation admins who can see (and control) who the other admins of their organisation are. Would be nice if the NRO admins had the same.

**Comment by restena-sw** [comment]
We are not the primary source of truth for this information, and only consume the "is-NRO-admin" status dynamically during login time from: the eduroam DB.

I believe the information you seek is available directly from the web view of eduroam DB, and it's best to consult that website.
