### ISSUE TITLE
404 Error in Overview Federation

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#71]
# Issue type
- [X ] Defect - Crash/memory corruption.
 
## Detail of issue
Link goes to 404

web/admin/overview_federation.php:175

echo "<tr><td colspan='8'><strong>" . sprintf(_("Your federation %s contains the following institutions: (<a href='%s'>Check their authentication server status</a>)"), '<span style="color:green">' . $thefed->name . '</span>', "/diag/action_fedcheck.php?fed=" . $thefed->identifier) . "</strong></td></tr>";

(added /diag infront of action_fedcheck.php)

**Comment by restena-sw** [comment]
I'm still meditating if the corresponding page and action can simply be deleted. With the upcoming user-side diagnostics tool, a federation overview can be assembled with entirely different means.
