### ISSUE TITLE
fedadmin option overwritten in DB

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#79]
# Issue type
- [X ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
# Defect/Feature description
'Save Data' in Management of User details removed any fedadmin attributes.

## How to reproduce issue
Add a user as a federation administrator (insert via DB)

Go to their profile and 'Save Data'

They're no longer a federation admin

## Detail of issue
Saving the data appears to only save the displayed data (and deletes what's currently there, including the fedadmin option).

**Comment by nevryn** [comment]
This one doesn't appear to have been fixed. 'Save data' still remove the fedadmin option.

**Comment by restena-sw** [comment]
Do you get any PHP notice/warning/errors in the log? If not I will need to set up a new DB instance with local user mgmt to reproduce this. Definitely something for next week only...

**Comment by nevryn** [comment]
On Fri, Aug 18, 2017 at 02:08:48PM +0000, Stefan Winter wrote:
>    Do you get any PHP notice/warning/errors in the log? If not I will need
>    to set up a new DB instance with local user mgmt to reproduce this.
>    Definitely something for next week only...

Not sure how useful this is but:

[Fri Aug 18 15:09:48.866507 2017] [:error] [pid 21964] [client 193.62.24.33:9288] PHP Warning:  mysqli_fetch_object() expects parameter 1 to be mysqli_result, boolean given in /opt/CAT/core/EntityWithDBProperties.php on line 126, referer: /https://cat-beta.govroam.uk/admin/edit_user.php

This from the debug log:

1503065388.8639 (5)  [/core/EntityWithDBProperties.php / exec / 174] DB ATTEMPT: SELECT option_name, option_lang, option_value, id AS row
                                                FROM user_options
                                                WHERE user_id = '106470707665778461289'
1503065388.8645 (5)  [/core/EntityWithDBProperties.php / exec / 122] DB ATTEMPT: DELETE FROM user_options WHERE user_id = "106470707665778461289" AND option_name NOT LIKE '%_file'
1503065388.8662 (5)  [/core/EntityWithDBProperties.php / exec / 124] DB ATTEMPT: SELECT row FROM user_options WHERE user_id = "106470707665778461289"
1503065388.8664 (1) ERROR: Cannot execute query in USER database - (hopefully escaped) query was 'SELECT row FROM user_options WHERE user_id = "106470707665778461289"'!1503065388.8667 (3) --- BEGIN constructing class core\User .

Mike


-- 
Mike Richardson
Currently on Secondment to JISC
*Plain text only please - attachments stripped on arrival*
