### ISSUE TITLE
'Check their authentication server status' fails

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#81]
# Issue type
- [ X] Defect - Unexpected behaviour (obvious or has been verified by a project member).
# Defect/Feature description

## How to reproduce issue
Click on 'Check their authentication server status'.

A page loads but only has

"Profiles with sufficient configuration, not marked as visible (C)

Inst Name	Profile Name	DNS Checks	Cert Checks	Reachability Checks	RADIUS/TLS Checks"

at the top.
 
## Detail of issue
[Fri Aug 11 08:19:56.043597 2017] [:error] [pid 10644] [client 193.62.24.33:63437] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to profilechecks() must be an instance of IdP, instance of core\\IdP given, called in /opt/CAT/web/diag/action_fedcheck.php on line 198 and defined in /opt/CAT/web/diag/action_fedcheck.php:18\nStack trace:\n#0 /opt/CAT/web/diag/action_fedcheck.php(198): profilechecks(Object(core\\IdP), Object(core\\ProfileRADIUS))\n#1 {main}\n  thrown in /opt/CAT/web/diag/action_fedcheck.php on line 18, referer: https://cat.govroam.uk/admin/overview_federation.php?

I *think* that the object being passed is a 'core\\IdP' not an 'IdP' but I'm not certain.

**Comment by restena-sw** [comment]
I have fixed the parameter type to the function.
Note that the entire diag/ part is in flux (hence also the 404 errors you are seeing) and I'm not sure if this code survives at all in its current form.

**Comment by nevryn** [comment]
This isn't working again:

[Fri Aug 18 14:47:58.661924 2017] [:error] [pid 21964] [client 193.62.24.33:8849] script '/opt/CAT/web/admin/action_fedcheck.php' not found or unable to stat, referer: https://cat-beta.govroam.uk/admin/overview_federation.php?invitation=SUCCESS&transportsecurity=ENCRYPTED

**Comment by restena-sw** [comment]
This is an entirely different problem than the original report in comment 1 above? It's more like you are now reporting a duplicate of #71?

I'm perfectly aware that action_fedcheck doesn't work. I'm still meditating if the corresponding page and action can simply be deleted. With the upcoming user-side diagnostics tool, a federation overview can be assembled with entirely different means.

The only thing I'm wondering is why this page is of much interest to @nevryn? This functionality was never in a released version of CAT and it was mostly my own playing ground to inform me/ musing on what to do and how to do it. 

I'm keeping this issue closed and would like to refer you to #71.

**Comment by nevryn** [comment]
Sorry, yes, I commented on the wrong one. It should have been on #71.

**Comment by nevryn** [comment]
I've never seen the page fully working so I've no idea how useful, or not, it would be.
