### ISSUE TITLE
404 when sending email with an invalid email address

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#85]
# Issue type
- [X ] Defect - Crash/memory corruption.

# Defect/Feature description
When sending an email a 404 is returned if an invalid email address is used.

## How to reproduce issue

Invite a new institution with an email address of 'd'.
 
## Detail of issue

[Wed Aug 16 15:08:57.016702 2017] [:error] [pid 19179] [client 193.62.24.33:40481] PHP Fatal error:  Uncaught Exception: sendinvite: The supplied value for email address is not a valid mail address! in /opt/CAT/web/admin/inc/sendinvite.inc.php:37\nStack trace:\n#0 {main}\n  thrown in /opt/CAT/web/admin/inc/sendinvite.inc.php on line 37, referer: https://cat-beta.govroam.uk/admin/overview_federation.php?

**Comment by nevryn** [comment]
On Thu, Aug 17, 2017 at 06:10:40AM +0000, Stefan Winter wrote:
>    Closed [1]#85 via [2]a75fc3f.
> 
>    --
>    You are receiving this because you authored the thread.
>    Reply to this email directly, [3]view it on GitHub, or [4]mute the
>    thread.

Thanks, but now there's a different error when you do submit an invalid address:

[Thu Aug 17 08:25:40.344596 2017] [:error] [pid 19558] [client 86.24.163.99:40001] PHP Notice:  Undefined variable: redirect_destination in /opt/CAT/web/admin/inc/sendinvite.inc.php on line 37, referer: /https://cat-beta.govroam.uk/admin/overview_federation.php?

Mike
-- 
Mike Richardson
Currently on Secondment to JISC
*Plain text only please - attachments stripped on arrival*

**Comment by restena-sw** [comment]
Hm, right, the destination hasn't been set yet. I pushed a change to fix this. Can you test it please?

**Comment by nevryn** [comment]
Yep, that seems to be fixed. A proper error message appears now.
