### ISSUE TITLE
edit_federation fails

### ISSUE THREAD

**Issue by twoln** [GEANT/CAT#86]
# Issue type
- Questions about the eduroamCAT or its usage should be sent to the [users mailing list](https://lists.geant.org/sympa/info/cat-users).

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [x] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description
When saving changes to the Federation data, an exception is called.

## How to reproduce issue

Edit federation details
 
## Detail of issue
The following exception appears in the log:
PHP Fatal error:  Uncaught TypeError: Argument 4 passed to web\\lib\\admin\\OptionParser::sendOptionsToDatabase() must be of the type string, null given, called in /opt/www/CAT-t/web/lib/admin/OptionParser.php on line 394 and defined in /opt/www/CAT-t/web/lib/admin/OptionParser.php:198\nStack trace:\n#0 /opt/www/CAT-t/web/lib/admin/OptionParser.php(394): web\\lib\\admin\\OptionParser->sendOptionsToDatabase(Object(core\\Federation), Array, Array, NULL, 0)\n#1 /opt/www/CAT-t/web/admin/edit_federation_result.php(38): web\\lib\\admin\\OptionParser->processSubmittedFields(Object(core\\Federation), Array, Array, Array)\n#2 {main}\n  thrown in /opt/www/CAT-t/web/lib/admin/OptionParser.php on line 198, referer: https://cat.eduroam.pl/trunk/admin/edit_federation.php

**Comment by restena-sw** [comment]
Can you try again? I introduced type safetly on "string" parameters, not knowing that a NULL is not acceptable value then. It is for optional arguments and can then be NULL, but sending an explicit NULL is not okay apparently.
The latest push should have a fix - but a few similar errors might be lurking...

**Comment by twoln** [comment]
All seems fine now.
