### ISSUE TITLE
Managed IdP link generating HTTP 500 error for new IdP

### ISSUE THREAD

**Issue by madrarua** [GEANT/CAT#89]
# Issue type
- Questions about the eduroamCAT or its usage should be sent to the [users mailing list](https://lists.geant.org/sympa/info/cat-users).

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [x] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description
I have successfully logged into cat-pilot.eduroam.org as an admin for a new IdP called "HEAnet test IdP". But when I click on the "Continue to Managed IdP properties" button I get "HTTP ERROR 500".

## How to reproduce issue
Browse directly to the URL of the page that generates this error: https://cat-pilot.eduroam.org/admin/edit_silverbullet.php?inst_id=31 

## Detail of issue
It's a new IdP that I created today, it is not linked to an entry in the eduroam database. I can confirm that I have "Enable Managed IdP" set to "on" under federation properties in cat-pilot. 

```text
**copy/paste evidence or feature request here. No links to 3rd party sites.
```

**Comment by restena-sw** [comment]
We are aware of the issue and are preparing an update to cat-pilot. I will update this issue when that is done.

**Comment by restena-sw** [comment]
The update has been completed, and functionality should be restored to nominal level. Please test this and let me know if there are still issues.

**Comment by madrarua** [comment]
Thanks Stefan. I can confirm it is working fine for me now. One of my clients was experiencing the same problem when trying to access their IdP after the update but I issued a new admin invite for them and it's all working fine for them now too.
