### ISSUE TITLE
Poor import checking in generated python script for Linux 

### ISSUE THREAD

**Issue by nicolasreich** [GEANT/CAT#93]
# Issue type

- [x] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [ ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect description
This import is problematic:
```
try:
    import dbus
except:
    subprocess.call(['python3'] + sys.argv)
    sys.exit(0)
```
## How to reproduce issue

Run the script on a system on which `dbus-python` is not installed.

## Detail of issue

It keeps creating subprocesses (assuming there is a binary called python3) until the system runs out of memory.

**Comment by twoln** [comment]
Indeed, bad. Fixed by calling python version check first and exiting before calling subprocess when the version equals 3.
Issue closed.

**Comment by twoln** [comment]
Fixed again
