### ISSUE TITLE
unset($this) causes a fatal error in PHP7.1

### ISSUE THREAD

**Issue by nicolasreich** [GEANT/CAT#94]
Starting from PHP7.1, `unset($this)` causes a fatal error (see the [PHP RFC](https://wiki.php.net/rfc/this_var)). There are two instances (I think), in `core/IDP.php:230` and in `core/AbstractProfile.php:360`.

**Comment by restena-sw** [comment]
See commit message for details of the fix.
Related: we are currently developing against PHP 7.0 as a baseline. In fact I tried an early patchlevel of 7.1 but the script execution went into erratic ways that our code can't possibly trigger. So I suspected a PHP 7.1 bug and stayed away from 7.1.
If recent 7.1 works for you, please do let us know and we can think about upping the baseline before release.

**Comment by nicolasreich** [comment]
Yes the parts I'm using work with 7.1. I'm mostly using the installer generation part though, not the front-end, not the CA part, not the database part,... so I can't know if it breaks something there. But the installer generation thing does work yes.

**Comment by restena-sw** [comment]
The break was when rendering the frontend's index.php.
