### ISSUE TITLE
basic.php calls locateUser() even if GEOIP is turned off (CAT 1.1.4)

### ISSUE THREAD

**Issue by sklemer1** [GEANT/CAT#95]
When using a mobile browser we get

```
[Mon Jan 22 10:49:48.516235 2018] [:error] [pid 15106] [client snip:47599] PHP Fatal error:  Uncaught Error: Call to undefined function geoip_record_by_name() in /var/www/CAT-1.1.4/core/UserAPI.php:487\nStack trace:\n#0 /var/www/CAT-1.1.4/web/basic.php(76): UserAPI->locateUser()\n#1 /var/www/CAT-1.1.4/web/basic.php(382): SimpleGUI->__construct()\n#2 {main}\n  thrown in /var/www/CAT-1.1.4/core/UserAPI.php on line 487, referer: https://cat.eduroam.de/basic.php?idp=SNIP&profile=SNIP
```
(php-geoip was not installed)
although we have GEOIP support turned off:

```php
#> cat config/config.php
[...]
    public static $GEOIP = array(
        'version' => 0,
        'geoip2-path-to-autoloader' => '/usr/share/GeoIP2/vendor/autoload.php',
        'geoip2-path-to-db' => '/usr/share/GeoIP2/DB/GeoLite2-City.mmdb',
    );
[...]
```

I think the error is also a problem for people using geoip version 2, because in web/basic.php always locateUser() is called which is the hardcoded version for geoip version 1:

```php
        if(isset($_REQUEST['country']) && $_REQUEST['country']) {
            $countryTest = strtoupper($_REQUEST['country']);
        } else {
            $L = $this->locateUser();
            if( $L['status'] == 'ok' ) {
                $countryTest = strtoupper($L['country']);
            } else {
                debug(2, "No coutry provided and unable to locate the address\n");
                $countryTest='NONE';
            }
        }
```

I fixed it for now by just installing php-geoip. I don't see a huge problem abandoning the support for running without geoip.

**Comment by restena-sw** [comment]
Hi,

1.1.x is quickly going EOL as we are close to a beta release of 2.0 already. Since you have already found a workaround for you, and there aren't many deployments besides that one, I would think we don't have to fix this in the current branch_1_1 code.

However, @twoln can you check if the same still happens in the modern skin on current master branch? If so, we should fix it there, if not, all the better :-)

**Comment by twoln** [comment]
basic.php together with the whole classic skin has been deleted, therefore we no longer have this problem.
