### ISSUE TITLE
Use crypto-safe token generator

### ISSUE THREAD

**Issue by sklemer1** [GEANT/CAT#97]
https://github.com/GEANT/CAT/blob/eb8838541ebbccec578fa2cf78042d90fd401f38/core/UserManagement.php#L250

seems to be some kind of hack. (why rand() and no crypto safe numbers? why explicitly set a maximum? if we don't trust rand() it doesn't really get better by using a hash on top of it and/or using it twice...).

I would propose to change it to either
```php
$token = bin2hex(openssl_random_pseudo_bytes(40,TRUE));
```
(http://php.net/manual/de/function.openssl-random-pseudo-bytes.php)

or (only PHP 7 and above)

```php
$token = bin2hex(random_bytes(40));
```

(http://php.net/manual/de/function.random-bytes.php)

The string length would still be 80.

**Comment by restena-sw** [comment]
The manual states that rand() is unsafe to use for cryptographic functions. I did not care about this as we are not using it for cryptographic purposes.

But there's always room for improvement :-)

Please send along a pull request for the latter option (random_bytes)  -CAT has a baseline PHP requirement of 7.0 so we can always expect this function to exist.
